# scheduler-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      component: custom-scheduler
  template:
    metadata:
      labels:
        component: custom-scheduler
    spec:
      serviceAccountName: my-scheduler
      containers:
        - name: kube-scheduler
          image: dockerhub_user/custom-scheduler:latest
          imagePullPolicy: Always
          command:
            - /usr/local/bin/kube-scheduler
            - --config=/etc/scheduler/kube-scheduler-config.yaml
            - --v=3
          volumeMounts:
            - name: config-volume
              mountPath: /etc/scheduler
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: my-scheduler-config
