---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  namespace: experiment
  labels:
    app: whispers
    carbonIntensity: "0.48"
spec:
  schedulerName: my-default-scheduler
  containers:
  - name: container
    image: polinux/stress
    command: ["stress", "--cpu", "1", "--vm", "1", "--vm-bytes", "1500M", "--timeout", "3600s"]
    resources:
      requests:
        memory: "1536Mi"
        cpu: "50m"
      limits:
        memory: "1536Mi"
        cpu: "50m"

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  namespace: experiment
  labels:
    app: whispers
    carbonIntensity: "0.62"
spec:
  schedulerName: my-default-scheduler
  containers:
  - name: container
    image: polinux/stress
    command: ["stress", "--cpu", "1", "--vm", "1", "--vm-bytes", "120M", "--timeout", "3600s"]
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "250m"

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  namespace: experiment
  labels:
    app: whispers
    carbonIntensity: "0.88"
spec:
  schedulerName: my-default-scheduler
  containers:
  - name: container
    image: polinux/stress
    command: ["stress", "--cpu", "2", "--vm", "1", "--vm-bytes", "60M", "--timeout", "3600s"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "2000m"
      limits:
        memory: "64Mi"
        cpu: "2000m"

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-4
  namespace: experiment
  labels:
    app: whispers
    carbonIntensity: "1.43"
spec:
  schedulerName: my-default-scheduler
  containers:
  - name: container
    image: polinux/stress
    command: ["stress", "--cpu", "1", "--vm", "1", "--vm-bytes", "60M", "--timeout", "3600s"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "50m"
