---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  namespace: experiment
  labels:
    app: sparks
    carbonIntensity: "0.71"
spec:
  schedulerName: my-default-scheduler
  containers:
  - name: container
    image: polinux/stress
    command: ["stress", "--cpu", "1", "--vm", "1", "--vm-bytes", "500M", "--timeout", "1800s"]
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  namespace: experiment
  labels:
    app: sparks
    carbonIntensity: "1.26"
spec:
  schedulerName: my-default-scheduler
  containers:
  - name: container
    image: polinux/stress
    command: ["stress", "--cpu", "1", "--vm", "1", "--vm-bytes", "500M", "--timeout", "1800s"]
    resources:
      requests:
        memory: "750Mi"
        cpu: "200m"
      limits:
        memory: "750Mi"
        cpu: "200m"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  namespace: experiment
  labels:
    app: sparks
    carbonIntensity: "0.99"
spec:
  schedulerName: my-default-scheduler
  containers:
  - name: container
    image: polinux/stress
    command: ["stress", "--cpu", "1", "--vm", "1", "--vm-bytes", "250M", "--timeout", "1800s"]
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "256Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-4
  namespace: experiment
  labels:
    app: sparks
    carbonIntensity: "1.65"
spec:
  schedulerName: my-default-scheduler
  containers:
  - name: container
    image: polinux/stress
    command: ["stress", "--cpu", "1", "--vm", "1", "--vm-bytes", "500M", "--timeout", "1800s"]
    resources:
      requests:
        memory: "750Mi"
        cpu: "500m"
      limits:
        memory: "750Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-5
  namespace: experiment
  labels:
    app: sparks
    carbonIntensity: "0.87"
spec:
  schedulerName: my-default-scheduler
  containers:
  - name: container
    image: polinux/stress
    command: ["stress", "--cpu", "1", "--vm", "1", "--vm-bytes", "1000M", "--timeout", "1800s"]
    resources:
      requests:
        memory: "1500Mi"
        cpu: "200m"
      limits:
        memory: "1500Mi"
        cpu: "200m"
