---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  namespace: experiment
  labels:
    app: emberlords
    carbonIntensity: "1.48"
spec:
  schedulerName: my-scheduler
  containers:
  - name: container
    image: polinux/stress
    command: ["stress", "--cpu", "1", "--vm", "1", "--vm-bytes", "128M", "--timeout", "1800s"]
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "256Mi"
        cpu: "200m"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  namespace: experiment
  labels:
    app: emberlords
    carbonIntensity: "1.05"
spec:
  schedulerName: my-scheduler
  containers:
  - name: container
    image: polinux/stress
    command: ["stress", "--cpu", "1", "--vm", "1", "--vm-bytes", "64M", "--timeout", "1800s"]
    resources:
      requests:
        memory: "128Mi"
        cpu: "750m"
      limits:
        memory: "128Mi"
        cpu: "750m"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  namespace: experiment
  labels:
    app: emberlords
    carbonIntensity: "1.42"
spec:
  schedulerName: my-scheduler
  containers:
  - name: container
    image: polinux/stress
    command: ["stress", "--cpu", "2", "--vm", "1", "--vm-bytes", "2000M", "--timeout", "1800s"]
    resources:
      requests:
        memory: "2048Mi"
        cpu: "1250m"
      limits:
        memory: "2048Mi"
        cpu: "1250m"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-4
  namespace: experiment
  labels:
    app: emberlords
    carbonIntensity: "1.02"
spec:
  schedulerName: my-scheduler
  containers:
  - name: container
    image: polinux/stress
    command: ["stress", "--cpu", "1", "--vm", "1", "--vm-bytes", "2000M", "--timeout", "1800s"]
    resources:
      requests:
        memory: "2048Mi"
        cpu: "500m"
      limits:
        memory: "2048Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-5
  namespace: experiment
  labels:
    app: emberlords
    carbonIntensity: "1.06"
spec:
  schedulerName: my-scheduler
  containers:
  - name: container
    image: polinux/stress
    command: ["stress", "--cpu", "2", "--vm", "1", "--vm-bytes", "1000M", "--timeout", "1800s"]
    resources:
      requests:
        memory: "1024Mi"
        cpu: "1500m"
      limits:
        memory: "1024Mi"
        cpu: "1500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-6
  namespace: experiment
  labels:
    app: emberlords
    carbonIntensity: "1.28"
spec:
  schedulerName: my-scheduler
  containers:
  - name: container
    image: polinux/stress
    command: ["stress", "--cpu", "1", "--vm", "1", "--vm-bytes", "64M", "--timeout", "1800s"]
    resources:
      requests:
        memory: "128Mi"
        cpu: "1000m"
      limits:
        memory: "128Mi"
        cpu: "1000m"
